name: actions-trial
on: [push]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
    - uses: actions/checkout@v2

    - name: Grant execute permission
    - run: chmod +x script.sh test_test_scropt.sh

    - name: Run the same script test
    - run: ./test_same.sh
